### ISSUE TITLE
Handle all errors properly

### ISSUE THREAD

**Issue by jcxldn** [Prouser123/xbl-web-api#1]
First of all, errors are not handled at all in some routes such as userstats and profile settings, and when errors are handled, only a few errors (namely 401 and 400) return a response code and message instead of empty data.

**To-Do**
- [ ] Handle errors in all routes
  - Add to existing routes
  - [ ] UserStats
  - [ ] ProfileSettings
  - [ ] TitleStats
  - [ ] LegacySearch
- [ ] Return error messages when appropriate
- [ ] Return the correct response code instead of empty data
- [ ] If an unexpected response code is recieved, do not return 200 and a blank message.
